import { createFileRoute } from "@tanstack/react-router";
import { CalendarDays, MapPin } from "lucide-react";
import { MemorialShell, PageIntro } from "@/components/memorial-shell";
import { portrait } from "@/lib/memorial-data";
import { useCmsContent } from "@/lib/cms-content";

export const Route = createFileRoute("/obituary")({ head: () => ({ meta: [
  { title: "Her Journey & Life Story — Mama Joyce" }, { name: "description", content: "The life story and enduring legacy of Joyce Dedo Narh." },
  { property: "og:title", content: "Her Journey & Life Story — Mama Joyce" }, { property: "og:description", content: "A life well lived, grounded in faith, family, and grace." }, { property: "og:type", content: "article" }, { name: "twitter:card", content: "summary_large_image" }, { property: "og:image", content: portrait }, { name: "twitter:image", content: portrait },
]}), component: Obituary });

function Obituary() { const content=useCmsContent("obituary"); return <MemorialShell><PageIntro eyebrow={content.eyebrow} title={content.title} subtitle={content.subtitle} /><article className="section-wrap max-w-5xl"><div className="grid gap-10 border-b border-border pb-12 md:grid-cols-[260px_1fr]"><img src={content.portraitUrl} alt={content.portraitAlt} className="aspect-[4/5] w-full object-cover shadow-lg"/><div><p className="eyebrow">{content.monographLabel}</p><h2 className="mt-3 font-display text-4xl text-primary">{content.name}</h2><p className="mt-2 font-display text-xl italic text-secondary">{content.nickname}</p><div className="mt-7 space-y-3 font-label text-sm text-muted-foreground"><p className="flex gap-3"><CalendarDays className="text-secondary" size={19}/><span><b>Sunrise:</b> {content.sunrise} • <b>Sunset:</b> {content.sunset}</span></p><p className="flex gap-3"><MapPin className="text-secondary" size={19}/>{content.locations}</p></div><p className="mt-7 border-l-2 border-secondary pl-5 font-display text-xl italic text-primary">{content.devotion}</p></div></div>{content.chapters.map((chapter,index)=><div key={`${chapter.number}-${index}`}><section className="mt-14"><p className="eyebrow">Chapter {chapter.number}</p><h2 className="mt-2 font-display text-3xl text-primary">{chapter.title}</h2><div className="mt-5 space-y-5 prose-memorial">{chapter.paragraphs.map((paragraph,i)=><p key={i}>{paragraph}</p>)}</div></section>{index===0&&<blockquote className="my-10 bg-primary px-8 py-10 text-center font-display text-2xl italic leading-relaxed text-primary-foreground">{content.quote}<footer className="mt-4 font-label text-xs not-italic uppercase tracking-widest text-primary-soft">{content.quoteSource}</footer></blockquote>}</div>)}</article></MemorialShell> }
