import { createFileRoute } from "@tanstack/react-router";
import { BookOpen, Church, Music, Printer, ScrollText } from "lucide-react";
import { MemorialShell, PageIntro } from "@/components/memorial-shell";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/order-of-service")({ head: () => ({ meta: [{ title: "Order of Service — Mama Joyce" }, { name: "description", content: "The burial service liturgy, songs of praise, scripture, and words of remembrance." }, { property: "og:title", content: "Order of Service — Mama Joyce" }, { property: "og:description", content: "Liturgy, songs of praise, and words of remembrance." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: OrderOfService });
const movements = [
 ["Processional Hymn","Congregational","“Great Is Thy Faithfulness” — Hymn of opening, solemn procession of clergy and family.",Music],
 ["Opening Prayer & Scripture Reading","Scripture","Psalm 23 & 1 Thessalonians 4:13–18 — Words of eternal hope and invocation of the Holy Spirit.",BookOpen],
 ["Memorial Hymn","Congregational","“Abide With Me” — Fast falls the eventide; the darkness deepens; Lord, with me abide.",Music],
 ["Reading of Biography & Tributes","Remembrance","A reflective account of Mama Joyce’s life journey, sacred maternal grace, and communal devotion.",ScrollText],
 ["Musical Interlude & Choir Ministration","Choral Anthem","Sacred chorale presentation commemorating lifelong faith and praise.",Music],
 ["Scripture Reading & Eulogy","Solemn Word","2 Timothy 4:7–8 — “I have fought the good fight, I have finished the race, I have kept the faith.”",BookOpen],
 ["The Sermon & Word of Comfort","Homily","Proclamation of the Gospel message and reassurance of resurrection peace to the bereaved.",Church],
 ["Prayer of Commendation & Thanksgiving","Commendation","Entrusting our mother into the gentle, everlasting arms of Almighty God.",Church],
 ["Recessional Hymn","Procession","“Guide Me, O Thou Great Jehovah” — Journeying forward in celestial guidance.",Music],
] as const;
function OrderOfService(){return <MemorialShell><PageIntro eyebrow="Order of Liturgy" title="Order of Service" subtitle="Liturgy, Songs of Praise & Words of Remembrance"/><div className="section-wrap max-w-4xl"><div className="border border-secondary/30 bg-accent/40 p-7 text-center"><Church className="mx-auto text-secondary"/><p className="mt-3 eyebrow">Theme of the Liturgy</p><p className="mt-3 font-display text-xl italic text-primary">“The Lord is my shepherd; I shall not want. Surely goodness and mercy shall follow me all the days of my life.”</p></div><div className="mt-12 flex items-end justify-between border-b border-border pb-5"><div><p className="eyebrow">Part I • Morning Ceremony</p><h2 className="mt-2 font-display text-3xl text-primary">Burial Service Liturgy</h2><p className="mt-1 font-label text-xs uppercase tracking-widest text-muted-foreground">9 Movements</p></div><Button variant="outline" size="sm" onClick={()=>window.print()}><Printer/>Print</Button></div><ol className="divide-y divide-border">{movements.map(([title,type,text,Icon],i)=><li key={title} className="grid gap-5 py-7 md:grid-cols-[48px_1fr_auto]"><span className="font-display text-2xl text-secondary">{String(i+1).padStart(2,"0")}</span><div><h3 className="font-display text-xl text-primary">{title}</h3><p className="mt-1 font-label text-[10px] font-bold uppercase tracking-widest text-secondary">{type}</p><p className="mt-3 prose-memorial text-sm">{text}</p></div><Icon className="text-secondary"/></li>)}</ol><div className="mt-10 bg-muted p-7"><p className="eyebrow">Keepsake Booklet Protocol</p><h3 className="mt-2 font-display text-2xl text-primary">Physical Order of Service Distribution</h3><p className="mt-3 prose-memorial text-sm">Physical, embossed memorial keepsakes with complete hymn lyrics, scriptural readings, and tribute texts will be handed to all congregants upon arrival at the sanctuary foyer.</p></div></div></MemorialShell>}