import { createFileRoute } from "@tanstack/react-router";
import { BookOpen, Church, Music, Printer, ScrollText } from "lucide-react";
import { MemorialShell, PageIntro } from "@/components/memorial-shell";
import { Button } from "@/components/ui/button";
import { useCmsContent } from "@/lib/cms-content";

export const Route = createFileRoute("/order-of-service")({ head: () => ({ meta: [{ title: "Order of Service — Mama Joyce" }, { name: "description", content: "The burial service liturgy, songs of praise, scripture, and words of remembrance." }, { property: "og:title", content: "Order of Service — Mama Joyce" }, { property: "og:description", content: "Liturgy, songs of praise, and words of remembrance." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: OrderOfService });
const icons=[Music,BookOpen,Music,ScrollText,Music,BookOpen,Church,Church,Music];
function OrderOfService(){const content=useCmsContent("order-of-service");return <MemorialShell><PageIntro eyebrow={content.eyebrow} title={content.title} subtitle={content.subtitle}/><div className="section-wrap max-w-4xl"><div className="border border-secondary/30 bg-accent/40 p-7 text-center"><Church className="mx-auto text-secondary"/><p className="mt-3 eyebrow">{content.themeLabel}</p><p className="mt-3 font-display text-xl italic text-primary">{content.theme}</p></div><div className="mt-12 flex items-end justify-between border-b border-border pb-5"><div><p className="eyebrow">{content.partLabel}</p><h2 className="mt-2 font-display text-3xl text-primary">{content.liturgyTitle}</h2><p className="mt-1 font-label text-xs uppercase tracking-widest text-muted-foreground">{content.movements.length} Movements</p></div><Button variant="outline" size="sm" onClick={()=>window.print()}><Printer/>{content.printLabel}</Button></div><ol className="divide-y divide-border">{content.movements.map((movement,i)=>{const Icon=icons[i]??Music;return <li key={i} className="grid gap-5 py-7 md:grid-cols-[48px_1fr_auto]"><span className="font-display text-2xl text-secondary">{String(i+1).padStart(2,"0")}</span><div><h3 className="font-display text-xl text-primary">{movement.title}</h3><p className="mt-1 font-label text-[10px] font-bold uppercase tracking-widest text-secondary">{movement.type}</p><p className="mt-3 prose-memorial text-sm">{movement.text}</p></div><Icon className="text-secondary"/></li>})}</ol><div className="mt-10 bg-muted p-7"><p className="eyebrow">{content.bookletLabel}</p><h3 className="mt-2 font-display text-2xl text-primary">{content.bookletTitle}</h3><p className="mt-3 prose-memorial text-sm">{content.bookletText}</p></div></div></MemorialShell>}
