import { createFileRoute } from "@tanstack/react-router";
import { Accessibility, CalendarDays, Camera, Check, Church, Clock, MapPin, ParkingCircle } from "lucide-react";
import { MemorialShell, PageIntro } from "@/components/memorial-shell";

export const Route = createFileRoute("/service-details")({ head: () => ({ meta: [{ title: "Service Details & Arrangements — Mama Joyce" }, { name: "description", content: "Burial and thanksgiving service times, venues, attire, and guest guidance." }, { property: "og:title", content: "Service Details & Arrangements — Mama Joyce" }, { property: "og:description", content: "Gathering in faith and thanksgiving to honor a cherished life." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: ServiceDetails });

const guidance = [
  [ParkingCircle, "Parking & Arrival", "Designated parking areas are reserved at both venues with parking marshals in attendance. Guests are gently encouraged to arrive 20–30 minutes ahead of scheduled time."],
  [Accessibility, "Accessibility Care", "Step-free ground access, wheelchair ramps, and reserved seating are designated for senior relatives, elderly congregants, and guests requiring mobility assistance."],
  [Camera, "Sanctuary Decorum", "To preserve reverence during prayers and homilies, mobile devices should be switched to silent mode. Only designated memorial media stewards may record the rites."],
] as const;
function Detail({ icon: Icon, title, children }: { icon: typeof CalendarDays; title: string; children: React.ReactNode }) { return <div className="flex gap-4 border-t border-border py-5"><Icon className="mt-1 shrink-0 text-secondary" size={22}/><div><p className="font-label text-xs font-bold uppercase tracking-widest text-muted-foreground">{title}</p><div className="mt-1 font-body leading-7 text-foreground">{children}</div></div></div> }
function ServiceDetails() { return <MemorialShell><PageIntro eyebrow="Ceremonial Order & Itinerary" title="Service Details & Arrangements" subtitle="Gathering in faith and thanksgiving to honor a cherished life"/><div className="section-wrap space-y-10"><ServiceCard label="Solemn Rites" title="Burial Service" order="Order I"><Detail icon={CalendarDays} title="Date & Time"><b>Saturday, 17th October 2026</b><br/><span className="text-secondary">9:00 AM Prompt</span></Detail><Detail icon={MapPin} title="Venue & Grounds"><b>Social Welfare Grounds</b><br/>La Nkwantanang, Madina, Greater Accra</Detail><Detail icon={Check} title="Prescribed Attire">Traditional Black & White or Formal Black Funeral Attire</Detail></ServiceCard><ServiceCard label="Celebration of Life" title="Thanksgiving Service" order="Order II"><Detail icon={Clock} title="Schedule Notice"><b>[Date & Time to be confirmed]</b><br/><span className="text-muted-foreground">Details will be updated as soon as arrangements conclude.</span></Detail><Detail icon={Church} title="Sanctuary"><b>ICGC Christ Temple East</b><br/>Teshie Rasta Rd, Teshie, Accra, Ghana</Detail><Detail icon={Check} title="Prescribed Attire">Joyful All-White or Elegant Black & White Thanksgiving Attire</Detail></ServiceCard><section><div className="text-center"><p className="eyebrow">Guest Guidance</p><h2 className="mt-3 font-display text-4xl text-primary">General Information & Etiquette</h2><p className="mx-auto mt-3 max-w-2xl prose-memorial">Helpful guidance to ensure the comfort, dignity, and serene reflection of all congregants.</p></div><div className="mt-10 grid gap-5 md:grid-cols-3">{guidance.map(([Icon,title,text])=><div key={title} className="border border-border bg-card p-6"><Icon className="text-secondary"/><h3 className="mt-5 font-display text-xl text-primary">{title}</h3><p className="mt-3 prose-memorial text-sm">{text}</p></div>)}</div></section><div className="bg-primary px-7 py-10 text-center text-primary-foreground"><p className="font-display text-2xl italic">“All are warmly welcomed to celebrate Mama Joyce’s life and legacy in peace and reverence.”</p><p className="mt-4 font-label text-xs uppercase tracking-[.18em] text-primary-soft">Medasi • Damirifa Due • Aseda</p></div></div></MemorialShell> }
function ServiceCard({label,title,order,children}:{label:string;title:string;order:string;children:React.ReactNode}) { return <section className="overflow-hidden border border-border bg-card shadow-sm"><header className="flex items-end justify-between bg-primary p-7 text-primary-foreground"><div><p className="font-label text-xs uppercase tracking-widest text-primary-soft">{label}</p><h2 className="mt-2 font-display text-3xl">{title}</h2></div><span className="font-display text-xl italic text-gold-soft">{order}</span></header><div className="px-7">{children}</div></section> }