/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ObituaryRouteImport } from './routes/obituary'
import { Route as OrderOfServiceRouteImport } from './routes/order-of-service'
import { Route as PhotoGalleryRouteImport } from './routes/photo-gallery'
import { Route as ServiceDetailsRouteImport } from './routes/service-details'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObituaryRoute = ObituaryRouteImport.update({
  id: '/obituary',
  path: '/obituary',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderOfServiceRoute = OrderOfServiceRouteImport.update({
  id: '/order-of-service',
  path: '/order-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotoGalleryRoute = PhotoGalleryRouteImport.update({
  id: '/photo-gallery',
  path: '/photo-gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceDetailsRoute = ServiceDetailsRouteImport.update({
  id: '/service-details',
  path: '/service-details',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/obituary': typeof ObituaryRoute
  '/order-of-service': typeof OrderOfServiceRoute
  '/photo-gallery': typeof PhotoGalleryRoute
  '/service-details': typeof ServiceDetailsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/obituary': typeof ObituaryRoute
  '/order-of-service': typeof OrderOfServiceRoute
  '/photo-gallery': typeof PhotoGalleryRoute
  '/service-details': typeof ServiceDetailsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/obituary': typeof ObituaryRoute
  '/order-of-service': typeof OrderOfServiceRoute
  '/photo-gallery': typeof PhotoGalleryRoute
  '/service-details': typeof ServiceDetailsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/obituary'
    | '/order-of-service'
    | '/photo-gallery'
    | '/service-details'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/obituary'
    | '/order-of-service'
    | '/photo-gallery'
    | '/service-details'
  id:
    | '__root__'
    | '/'
    | '/obituary'
    | '/order-of-service'
    | '/photo-gallery'
    | '/service-details'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ObituaryRoute: typeof ObituaryRoute
  OrderOfServiceRoute: typeof OrderOfServiceRoute
  PhotoGalleryRoute: typeof PhotoGalleryRoute
  ServiceDetailsRoute: typeof ServiceDetailsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obituary': {
      id: '/obituary'
      path: '/obituary'
      fullPath: '/obituary'
      preLoaderRoute: typeof ObituaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-of-service': {
      id: '/order-of-service'
      path: '/order-of-service'
      fullPath: '/order-of-service'
      preLoaderRoute: typeof OrderOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photo-gallery': {
      id: '/photo-gallery'
      path: '/photo-gallery'
      fullPath: '/photo-gallery'
      preLoaderRoute: typeof PhotoGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-details': {
      id: '/service-details'
      path: '/service-details'
      fullPath: '/service-details'
      preLoaderRoute: typeof ServiceDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ObituaryRoute: ObituaryRoute,
  OrderOfServiceRoute: OrderOfServiceRoute,
  PhotoGalleryRoute: PhotoGalleryRoute,
  ServiceDetailsRoute: ServiceDetailsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
