/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ObituaryRouteImport } from './routes/obituary'
import { Route as OrderOfServiceRouteImport } from './routes/order-of-service'
import { Route as PhotoGalleryRouteImport } from './routes/photo-gallery'
import { Route as ServiceDetailsRouteImport } from './routes/service-details'
import { Route as TributesRouteImport } from './routes/tributes'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ObituaryRoute = ObituaryRouteImport.update({
  id: '/obituary',
  path: '/obituary',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderOfServiceRoute = OrderOfServiceRouteImport.update({
  id: '/order-of-service',
  path: '/order-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotoGalleryRoute = PhotoGalleryRouteImport.update({
  id: '/photo-gallery',
  path: '/photo-gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceDetailsRoute = ServiceDetailsRouteImport.update({
  id: '/service-details',
  path: '/service-details',
  getParentRoute: () => rootRouteImport,
} as any)
const TributesRoute = TributesRouteImport.update({
  id: '/tributes',
  path: '/tributes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/obituary': typeof ObituaryRoute
  '/order-of-service': typeof OrderOfServiceRoute
  '/photo-gallery': typeof PhotoGalleryRoute
  '/service-details': typeof ServiceDetailsRoute
  '/tributes': typeof TributesRoute
  '/admin': typeof AuthenticatedAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/obituary': typeof ObituaryRoute
  '/order-of-service': typeof OrderOfServiceRoute
  '/photo-gallery': typeof PhotoGalleryRoute
  '/service-details': typeof ServiceDetailsRoute
  '/tributes': typeof TributesRoute
  '/admin': typeof AuthenticatedAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/obituary': typeof ObituaryRoute
  '/order-of-service': typeof OrderOfServiceRoute
  '/photo-gallery': typeof PhotoGalleryRoute
  '/service-details': typeof ServiceDetailsRoute
  '/tributes': typeof TributesRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/obituary'
    | '/order-of-service'
    | '/photo-gallery'
    | '/service-details'
    | '/tributes'
    | '/admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/obituary'
    | '/order-of-service'
    | '/photo-gallery'
    | '/service-details'
    | '/tributes'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/obituary'
    | '/order-of-service'
    | '/photo-gallery'
    | '/service-details'
    | '/tributes'
    | '/_authenticated/admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ObituaryRoute: typeof ObituaryRoute
  OrderOfServiceRoute: typeof OrderOfServiceRoute
  PhotoGalleryRoute: typeof PhotoGalleryRoute
  ServiceDetailsRoute: typeof ServiceDetailsRoute
  TributesRoute: typeof TributesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obituary': {
      id: '/obituary'
      path: '/obituary'
      fullPath: '/obituary'
      preLoaderRoute: typeof ObituaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-of-service': {
      id: '/order-of-service'
      path: '/order-of-service'
      fullPath: '/order-of-service'
      preLoaderRoute: typeof OrderOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photo-gallery': {
      id: '/photo-gallery'
      path: '/photo-gallery'
      fullPath: '/photo-gallery'
      preLoaderRoute: typeof PhotoGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-details': {
      id: '/service-details'
      path: '/service-details'
      fullPath: '/service-details'
      preLoaderRoute: typeof ServiceDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tributes': {
      id: '/tributes'
      path: '/tributes'
      fullPath: '/tributes'
      preLoaderRoute: typeof TributesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ObituaryRoute: ObituaryRoute,
  OrderOfServiceRoute: OrderOfServiceRoute,
  PhotoGalleryRoute: PhotoGalleryRoute,
  ServiceDetailsRoute: ServiceDetailsRoute,
  TributesRoute: TributesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
